run_mode: "self_debug" # e.g. normal or self_debug
plotting_language: "python"
debug:
  top_k: 3
  output_dir: ""
paths:
  out_folder: ""
  dataset_folder: "dataset"
  results_filename: "results.json"
  bench_stat_filename: ""
  error_rate_file: ""
benchmark_types: ["vis", "task"]
data_descriptor: "head" # data descriptor. Options: "pycharm", "datalore", "lida", "head", "describe", "empty"

model_plot_gen:
  names: ["TIGER-Lab/VisCoder2-7B"]
  parameters: # List of additional model parameters.
    temperature: 0.0
model_judge:
  name: "openai/gpt-4.1"
  parameters: # List of additional model parameters.
    temperature: 0.0